# Generated by Django 5.2.16 on 2026-07-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('fleet_manager', 'Fleet Manager'), ('dispatcher', 'Dispatcher'), ('safety_officer', 'Safety Officer'), ('financial_analyst', 'Financial Analyst')], max_length=50),
        ),
    ]
