# Generated by Django 5.2.16 on 2026-07-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('license_category', models.CharField(max_length=50)),
                ('license_expiry_date', models.DateField()),
                ('contact_number', models.CharField(max_length=50)),
                ('safety_score', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('off_duty', 'Off Duty'), ('suspended', 'Suspended')], default='available', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
