# Generated by Django 5.2.16 on 2026-07-12 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name_model', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('max_load_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odometer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_trip', 'On Trip'), ('in_shop', 'In Shop'), ('retired', 'Retired')], default='available', max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='vehicles.vehicle')),
            ],
        ),
    ]
