/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "outline": "#727785",
        "on-tertiary-container": "#fcfcff",
        "on-primary-fixed": "#001a42",
        "on-surface-variant": "#424754",
        "outline-variant": "#c2c6d6",
        "tertiary-container": "#007cb1",
        "secondary": "#006b5f",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#d9e3f6",
        "primary-fixed": "#d8e2ff",
        "primary-container": "#2170e4",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-container": "#006f64",
        "on-surface": "#121c2a",
        "surface-container-low": "#eff4ff",
        "on-tertiary-fixed-variant": "#004c6e",
        "tertiary-fixed-dim": "#89ceff",
        "background": "#f8f9ff",
        "surface-container-high": "#dee9fc",
        "secondary-container": "#6df5e1",
        "tertiary": "#00628d",
        "surface-container-highest": "#d9e3f6",
        "tertiary-fixed": "#c9e6ff",
        "on-secondary-fixed-variant": "#005048",
        "on-primary-fixed-variant": "#004395",
        "on-background": "#121c2a",
        "secondary-fixed": "#71f8e4",
        "surface-tint": "#005ac2",
        "inverse-on-surface": "#eaf1ff",
        "surface-bright": "#f8f9ff",
        "primary-fixed-dim": "#adc6ff",
        "surface-dim": "#d0dbed",
        "on-tertiary-fixed": "#001e2f",
        "surface-container": "#e6eeff",
        "secondary-fixed-dim": "#4fdbc8",
        "on-primary": "#ffffff",
        "on-primary-container": "#fefcff",
        "primary": "#0058be",
        "surface": "#f8f9ff",
        "inverse-surface": "#27313f",
        "on-secondary-fixed": "#00201c",
        "inverse-primary": "#adc6ff",

        // Sage & minty wash options from DESIGN.md
        "sage-nav": "#EEF4F0",
        "mint-bg": "#E0F8D6",
        "mint-card": "#B3E5B7",
        "dark-gray": "#1F2937",
        "electric-blue": "#3B82F6"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
      },
      spacing: {
        "base": "4px",
        "xs": "0.5rem",
        "sm": "1rem",
        "md": "1.5rem",
        "lg": "2rem",
        "xl": "3rem",
        "container-margin": "24px",
        "gutter": "16px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      }
    },
  },
  plugins: [],
}
