# Generated by Django 5.2.16 on 2026-07-12 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fuel_expenses', '0001_initial'),
        ('trips', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellog',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fuel_logs', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_logs', to='vehicles.vehicle'),
        ),
    ]
